name: CI for ML Project (MLflow)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-run-mlflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Miniconda and create environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.12
          environment-file: MLProject/conda.yaml # Buat lingkungan dari file ini
          # Kita tidak menggunakan `activate-environment` di sini agar lebih manual kontrol
          # agar kita bisa memastikan aktivasi di setiap `run` command.

      - name: Conda info (for debugging)
        # ✅ Selalu aktifkan lingkungan di setiap blok `run` jika tidak yakin sudah aktif
        run: |
          conda activate mlflow-env # Aktifkan lingkungan di sini
          conda info
          conda env list
          conda list

      - name: Run MLflow Project
        run: |
          conda activate mlflow-env # ✅ Aktifkan lingkungan di sini lagi
          cd MLProject
          mlflow run . -P data_path=HDS_preprocessing.csv

      - name: Verify MLflow Run (Optional)
        run: |
          conda activate mlflow-env # ✅ Aktifkan lingkungan di sini lagi
          if [ -d "MLProject/mlruns" ]; then
            echo "MLflow run artifacts found in MLProject/mlruns."
            ls -R MLProject/mlruns
          else
            echo "MLflow run artifacts not found!"
            exit 1
          fi
