name: CI for ML Project (MLflow)
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-run-mlflow:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash -l {0}  # ✅ Penting: Gunakan login shell untuk conda
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.12
          activate-environment: mlflow-env
          environment-file: MLProject/conda.yaml
          auto-activate-base: false
      
      - name: Cache Conda environment
        uses: actions/cache@v4
        with:
          path: |
            ~/conda_pkgs_dir
            ~/.conda/envs
          key: ${{ runner.os }}-conda-${{ hashFiles('MLProject/conda.yaml') }}
          restore-keys: |
            ${{ runner.os }}-conda-
      
      - name: Verify conda environment and MLflow installation
        run: |
          echo "Current conda environment:"
          conda info
          echo "Active environment:"
          conda env list
          echo "Python location:"
          which python
          echo "MLflow location:"
          which mlflow || echo "MLflow not found in PATH"
          echo "Installed packages:"
          conda list | grep -E "(mlflow|python)"
      
      - name: Install MLflow if not present
        run: |
          if ! command -v mlflow &> /dev/null; then
            echo "MLflow not found, installing..."
            conda install -c conda-forge mlflow -y
          else
            echo "MLflow is already installed"
          fi
      
      - name: Run MLflow Project
        run: |
          cd MLProject
          echo "Current directory: $(pwd)"
          echo "MLflow version: $(mlflow --version)"
          mlflow run . -P data_path=HDS_preprocessing.csv
      
      - name: Verify MLflow Run
        run: |
          cd MLProject
          if [ -d "mlruns" ]; then
            echo "✅ MLflow run artifacts found in mlruns."
            ls -la mlruns/
            # Tampilkan struktur direktori mlruns
            find mlruns -type f -name "*.yaml" -o -name "*.json" -o -name "*.txt" | head -10
          else
            echo "❌ MLflow run artifacts not found!"
            exit 1
          fi
      
      - name: Upload MLflow artifacts (Optional)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: mlflow-artifacts
          path: MLProject/mlruns/
          retention-days: 30
