name: CI for ML Project (MLflow)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-run-mlflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Conda environment
        uses: actions/cache@v4 # Menggunakan action cache
        id: cache-conda-env # Memberikan ID agar bisa direferensikan
        with:
          path: |
            /usr/share/miniconda/envs/mlflow-env # Path ke lingkungan Conda Anda
            ~/.conda/pkgs # Path ke paket Conda cache
          key: ${{ runner.os }}-conda-${{ hashFiles('MLProject/conda.yaml') }} # Kunci cache berdasarkan OS dan hash file conda.yaml
          restore-keys: |
            ${{ runner.os }}-conda-

      - name: Set up Miniconda and activate environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.12 # Pastikan sesuai dengan conda.yaml Anda
          activate-environment: mlflow-env # Kembali menggunakan parameter ini
          environment-file: MLProject/conda.yaml # ✅ Ini akan membuat/memperbarui lingkungan

      - name: Conda info (for debugging)
        # Lingkungan 'mlflow-env' seharusnya sudah aktif otomatis dari action setup-miniconda
        # Tidak perlu `conda activate` manual lagi di sini
        run: |
          conda info
          conda env list
          conda list # Ini akan menampilkan paket yang terinstal di mlflow-env

      - name: Run MLflow Project
        # Karena `activate-environment` sudah mengaktifkannya, perintah ini akan berjalan di lingkungan yang benar.
        run: |
          cd MLProject
          mlflow run . -P data_path=HDS_preprocessing.csv

      - name: Verify MLflow Run (Optional)
        run: |
          # Perintah ini juga akan berjalan di lingkungan yang sudah aktif
          cd MLProject # Pastikan ada di direktori MLProject jika perlu
          if [ -d "mlruns" ]; then
            echo "MLflow run artifacts found in mlruns."
            ls -R mlruns
          else
            echo "MLflow run artifacts not found!"
            exit 1
          fi
