1s
Run # Ini adalah baris kunci untuk menginisialisasi shell untuk Conda
  # Ini adalah baris kunci untuk menginisialisasi shell untuk Conda
  # Pastikan jalur ke `etc/profile.d/conda.sh` benar.
  # Atau, bisa juga `eval "$(conda shell hook)"` atau `source "$(conda info --base)/etc/profile.d/conda.sh"`
  source /usr/share/miniconda/etc/profile.d/conda.sh
  conda activate mlflow-env
  shell: /usr/bin/bash -e {0}
  env:
    INPUT_RUN_POST: true
    CONDA: /usr/share/miniconda

EnvironmentNameNotFound: Could not find conda environment: mlflow-env
You can list all discoverable environments with `conda info --envs`.


Error: Process completed with exit code 1.
