name: CI for ML Project (MLflow)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-run-mlflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Miniconda and create environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.12
          environment-file: MLProject/conda.yaml

      - name: Initialize Conda Shell and Activate Environment
        run: |
          # Ini adalah baris kunci untuk menginisialisasi shell untuk Conda
          # Pastikan jalur ke `etc/profile.d/conda.sh` benar.
          # Atau, bisa juga `eval "$(conda shell hook)"` atau `source "$(conda info --base)/etc/profile.d/conda.sh"`
          source /usr/share/miniconda/etc/profile.d/conda.sh
          conda activate mlflow-env

      - name: Conda info (for debugging)
        run: |
          conda info
          conda env list
          conda list

      - name: Run MLflow Project
        run: |
          cd MLProject
          mlflow run . -P data_path=HDS_preprocessing.csv

      - name: Verify MLflow Run (Optional)
        run: |
          cd MLProject
          if [ -d "mlruns" ]; then
            echo "MLflow run artifacts found in mlruns."
            ls -R mlruns
          else
            echo "MLflow run artifacts not found!"
            exit 1
          fi
