name: CI for ML Project (MLflow)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-run-mlflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Miniconda and activate environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.12 # Pastikan sesuai dengan conda.yaml
          activate-environment: mlflow-env # Nama lingkungan dari conda.yaml Anda
          # ✅ PENTING: Gunakan parameter `environment-file` di sini
          environment-file: MLProject/conda.yaml # Ini akan membuat dan mengisi lingkungan

      - name: Conda info (for debugging)
        run: |
          conda info
          conda env list
          conda activate mlflow-env # Pastikan lingkungan aktif
          conda list # Lihat semua paket yang terinstal

      # ✅ Hapus langkah 'Create and activate Conda environment from conda.yaml' yang sebelumnya ada
      # Langkah ini tidak lagi diperlukan karena 'setup-miniconda' sudah menanganinya

      - name: Run MLflow Project
        run: |
          conda activate mlflow-env # Pastikan lingkungan tetap aktif (walaupun seharusnya sudah aktif)
          cd MLProject
          mlflow run . -P data_path=HDS_preprocessing.csv

      - name: Verify MLflow Run (Optional)
        run: |
          if [ -d "MLProject/mlruns" ]; then
            echo "MLflow run artifacts found in MLProject/mlruns."
            ls -R MLProject/mlruns
          else
            echo "MLflow run artifacts not found!"
            exit 1
          fi
